### ISSUE TITLE
Giving Errror

### ISSUE THREAD

**Issue by Script-Kiddie-JKB** [cheems/BlackPearl-Tutorial-Thread-Generator#3]
Was working fine few days ago , now giving error kind of some url error, 
![image](https://user-images.githubusercontent.com/78461084/124222967-6aab9c00-db20-11eb-9469-a7a95c3d1060.png)

**Comment by cheems** [comment]
A change in course image link pattern may be the thing caused to this. Will check it out this weekend. But if you can have a look and make a pull request, it is also appreciated

**Comment by cheems** [comment]
Fixed!
