### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by evilbros7** [cheems/BlackPearl-Tutorial-Thread-Generator#5]
Getting this error..!!

![image](https://user-images.githubusercontent.com/69081291/143685510-1df4fedd-83be-47c8-b925-fd68fb088b8b.png)

**Comment by menukaonline** [comment]
Your provided link was invalid.

Even you provided a valid link, it would still be failed coz the some parts of the script need to be updated with regex. I will look into that when I got some time
